### ISSUE TITLE
Breaks Capistrano deploy

### ISSUE THREAD

**Issue by kirillsalykin** [platanus/capistrano3-nginx#28]
When doing capistrano deploy it hangs on sudo mkdir /shared/log '[sudo] password for'

**Comment by RossBarnie** [comment]
That looks like an issue with your deploy user configuration, as in that user should be allowed to sudo without a password, otherwise it will "hang" (it's not really hanging it's just waiting on user input that will never come).

**Comment by a-ta-ta** [comment]
I have the same issue. I tried [Capistrano official guide](http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/#toc_8)
but it doesn't affect on my deployment.

**Comment by xainbutt** [comment]
is there any way to pass this..i have tried multiple things but in vain..

**Comment by RossBarnie** [comment]
@xainbutt Does your deploy user have passwordless sudo configured?

**Comment by xainbutt** [comment]
no i dont think so...
are you talking about this..?
set :use_sudo,        true

**Comment by RossBarnie** [comment]
No, that means that the user on the server is trying to use sudo. To test if you have passwordless sudo set up, log in to the server as your deploy user, in my case the user is set in my `config/deploy/production.rb` file:

```ruby
server "obfuscated.server.com", user: 'bob'
```
So bob is the user that runs any necessary commands on the server, and the one that needs passwordless sudo. Log in to the server as this user, and attempt to run any command with sudo. If you receive a password prompt (ie you have to enter a password) you need to set up passwordless sudo, otherwise you have a probably different problem. As always with bug reports/issues if you provide the commands you are running and their output then it's easier to see what the problem is and provide help.

**Comment by xainbutt** [comment]
@RossBarnie  i have included nginx tasks(as mentioned in docs) in capfile, deploying the app with cap production deploy command, and when it hits nginx:create_log_paths, it hangs up..and if i comment out the task in capfile and use capistrano's execute method to restart nginx, it still hangs up..

execute('sudo service nginx restart')


task :restart do
    on roles(:app), in: :sequence, wait: 5 do
      invoke 'puma:restart'
      execute('sudo service nginx restart')  <-----
    end
  end

**Comment by xainbutt** [comment]
right now i have this configuration and added the user as you suggested
server 'someserver.com', port: 22, roles: [:web, :app, :db], primary: true, user: 'deploy'

**Comment by RossBarnie** [comment]
Ok so as I've said, you are trying to use sudo, which prompts for a password unless you've set up passwordless sudo. Google is your friend for configuring that.

**Comment by blackjid** [comment]
you can do something like this.
go into the server and run `sudo visudo`

there you can setup which users get sudoless support for specific commands, you don't want to let the user execute just everything without password prompt.

```
deploy ALL=(ALL) NOPASSWD: /usr/bin/service nginx *, /usr/sbin/nginx_ensite, /usr/sbin/nginx_dissite, /bin/mv /tmp/unicorn.rb *, /bin/mv /tmp/nginx.conf *, /usr/sbin/nginx -t, /bin/ln -nfs *, /bin/mkdir *
```

I've been using this line for our servers that use `capistrano3-nginx` (this is ubuntu 14.04 btw, you os might be different)
